# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user_first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('user_last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('monthly_adwords_spend', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monthly Google Adwords Spend')),
                ('quote', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quote')),
                ('type', models.CharField(choices=[('automatic', 'Automatic'), ('estimate', 'Estimate')], max_length=20, verbose_name='Type')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
