# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:45
from __future__ import unicode_literals

from django.db import migrations


def convert_to_micro_amounts(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')

    for quote in Quote.objects.all():
        quote.monthly_adwords_spend *= 10**6
        quote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20170925_1641'),
    ]

    operations = [
        migrations.RunPython(convert_to_micro_amounts),
    ]
