# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20170925_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='monthly_adwords_spend',
            field=models.BigIntegerField(verbose_name='Monthly Google Adwords Spend'),
        ),
    ]
