# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name_plural': 'site config'},
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='new_user_alert_email',
            field=models.EmailField(blank=True, help_text='The email address to which to send an email upon a new user registering.  Leave blank to not send an email.', max_length=254, null=True),
        ),
    ]
