# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_managed', models.BooleanField()),
                ('target_cpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cycle_period_days', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adword_keyword_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_max_cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paused', models.BooleanField()),
                ('action', models.CharField(choices=[('increase_cpc', 'increase_cpc'), ('decrease_cpc', 'decrease_cpc'), ('no_action', 'no_action'), ('paused', 'paused')], max_length=50)),
                ('previous_max_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('increased_bids', models.PositiveIntegerField()),
                ('decreased_bids', models.PositiveIntegerField()),
                ('unchanged_bids', models.PositiveIntegerField()),
                ('keywords_paused', models.PositiveIntegerField()),
            ],
        ),
    ]
