# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_campaign_max_cpc_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='adwords_campaign_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
