# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_campaign_adwords_campaign_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordevent',
            old_name='adword_keyword_id',
            new_name='adwords_keyword_id',
        ),
    ]
