# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_delete_keywordevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='max_cpc_limit',
            field=models.PositiveIntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
