# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:37
from __future__ import unicode_literals

from django.db import migrations


def convert_microamounts(apps, schema_editor):
    Campaign = apps.get_model('reports', 'Campaign')

    for campaign in Campaign.objects.all():
        campaign.target_cpa *= 10**4
        campaign.max_cpc_limit *= 10**4

        campaign.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20170203_1136'),
    ]

    operations = [
        migrations.RunPython(convert_microamounts),
    ]
