# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20170203_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
