# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20170413_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='conversion_type',
            field=models.TextField(choices=[('cpa', 'Cost per Acquisition'), ('margin', 'Margin')], default='cpa', max_length=6),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_conversion_margin',
            field=models.DecimalField(decimal_places=3, default=0, help_text='The average margin you would like to achieve', max_digits=5, verbose_name='Target Margin in %'),
        ),
    ]
