# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20170927_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='conversion_type',
            field=models.CharField(choices=[('cpa', 'Cost per Acquisition'), ('margin', 'Margin')], default='cpa', max_length=6),
        ),
    ]
