# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20170927_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_managed',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Manage Using Captivise'),
        ),
    ]
